language: python

python:
    - "2.7"

before_install:
    - pip install setuptools --upgrade
    - pip install pyexcel
    - pip install ipython==5.3.0
    - pip install -r requirements.txt --use-mirrors

install:
    - pip install .

script:
    - echo "foo"

notifications:
    email: false
